# db ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa ??
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: ture
        format_sql: ture
        use_sql_comments: true

# jwt secret key ??
jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==


# SWAGGER 설정
springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tag-sorter: alpha

  show-login-endpoint: true

