# db ??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

# jpa ??
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: ture
        format_sql: ture
        use_sql_comments: true

# jwt secret key ??
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb


# SWAGGER 설정
springdoc:
  swagger-ui:
    path: /api-test
    groups-order: DESC
    tag-sorter: alpha

